---
- hosts: web
  remote_user: root

  tasks:
  - name: Update System
    apt:
      update-cache: yes
      upgrade: safe
    tags:
      - update

  - name: Check Docker Container
    docker:
      name: gitlab_7.10.4
      image: gitlab:7.10.4
      state: reloaded
      detach: true
      restart_policy: always
      ports:
      - 0.0.0.0:2222:22
      - 0.0.0.0:8888:80
      volumes_from:
      - gitlab_data
